### ISSUE TITLE
Incorrect translate for null values

### ISSUE THREAD

**Issue by PedroWilliam** [henkmollema/Dommel#106]
Hi, 

I try to execute the following select:

`var listCards = conn.Select<CardModel>(c => c.DateClosed == null);`
`var listCards = conn.Select<CardModel>(c => c.DateClosed != null);`

The generated SQL Query looks like this:

`"SELECT * FROM Cards WHERE `DateClosed` = null"`

`"SELECT * FROM Cards WHERE `DateClosed` <> null"`

The translations should be:

`"SELECT * FROM Cards WHERE `DateClosed` IS null"`

`"SELECT * FROM Cards WHERE `DateClosed` IS NOT null"`

**Comment by henkmollema** [comment]
Which database are you using?

**Comment by PedroWilliam** [comment]
Hi @henkmollema 
I'm using MySQL
