### ISSUE TITLE
Add ability to pass down "buffered" parameter

### ISSUE THREAD

**Issue by ffandreassoroko** [henkmollema/Dommel#107]
Hey, 
first of all - thanks for the great lib! 

ist there a way to pass down the "buffered" paramter ? couldnt find anything..
if not it would be great if you could add this feature, thanks!

**Comment by henkmollema** [comment]
Thanks for creating this issue. 

As far as I know it is not possible to pass the buffered parameter to **async** methods in Dapper, only to non-async methods. Hence why the buffered parameter is only present in non-async methods of Dommel as well. E.g. `Get()` vs `GetAsync()`.
