### ISSUE TITLE
Exception thrown when using InsertAsync

### ISSUE THREAD

**Issue by zscaiosi** [henkmollema/Dommel#115]
Hi, I am using Dommel at my project and when trying to make an INSERT using Task<T> CreateAsync(T Entity) the following Exception is thrown:

> "Cannot insert the value NULL into column '{{column name. It is a PK}}', table '{{table name}}'; column does not allow nulls. INSERT fails.\r\nThe statement has been terminated."

The column is a Primary Key, and at my Entity's Class I annotated it with [Key] (KeyAtttribute), and a proper value IS SET to that property when I execute CreateAsync(T Entity).

I decided to check the SQL statement building process within the source code, and the following code excerption makes me confused:

`private static string BuildInsertQuery(IDbConnection connection, Type type)
        {
            if (!_insertQueryCache.TryGetValue(type, out string sql))
            {
                var tableName = Resolvers.Table(type);

                var keyProperty = Resolvers.KeyProperty(type, out bool isIdentity, out DatabaseGeneratedOption databaseGenerated);

                var typeProperties = new List<PropertyInfo>();
                foreach (var typeProperty in Resolvers.Properties(type))
                {
                    if (typeProperty == keyProperty)
                    {
                        if (isIdentity && databaseGenerated == DatabaseGeneratedOption.Identity)
                        {
                            // Skip key properties marked as an identity column.
                            continue;
                        }
                    }

                    if (typeProperty.GetSetMethod() != null)
                    {
                        typeProperties.Add(typeProperty);
                    }
                }

                var columnNames = typeProperties.Select(Resolvers.Column).ToArray();
                var paramNames = typeProperties.Select(p => "@" + p.Name).ToArray();

                var builder = GetBuilder(connection);
                sql = builder.BuildInsert(tableName, columnNames, paramNames, keyProperty);

                _insertQueryCache.TryAdd(type, sql);
            }

            return sql;
        }`.

Why should it skip the typeProperty == keyProperty? When it happens, my property and its value are not passed to the SQL statement and thereby not **_inserted_** into the table right?

Can someone give me a glance on how to fix it?
Thanks!

**Comment by henkmollema** [comment]
This is currently by design. Dommel assumes that the primary key is always generated by the database. I've opened #123 to figure out whether Dommel can support non-generated primary keys.
