### ISSUE TITLE
GetAsync mapping to wrong Entity

### ISSUE THREAD

**Issue by tavaresaraujo** [henkmollema/Dommel#117]
When I call a API endpoint that gets a "Camera" by Id, it is returned what I expect.
When I call the same API endpoint to get a "Group" I get a error on mapping.

![image](https://user-images.githubusercontent.com/43425012/58102966-8c539e80-7bb8-11e9-8e16-e337a864d893.png)

Seems that When I got the "Camera" Dommel is considering only its mapping even if I call get a "Group".

I´m using:
C# 7 > WebApi 2 > asp net core 2.2
Dapper 1.60.6 > Dapper.FluentMap 1.8.0 > Dapper.FluentMap.Dommel > 1.7.0

So here is the Pipe line
1 - First my web api project
![image](https://user-images.githubusercontent.com/43425012/58103098-c624a500-7bb8-11e9-8690-a45c0b7556ab.png)
![image](https://user-images.githubusercontent.com/43425012/58103170-e8b6be00-7bb8-11e9-9e00-01d7d2bfde6a.png)
![image](https://user-images.githubusercontent.com/43425012/58103208-f66c4380-7bb8-11e9-8b3e-00cf63929ca0.png)

2 - Calls my Application layer
![image](https://user-images.githubusercontent.com/43425012/58103261-10a62180-7bb9-11e9-9df9-ea79e06e3af6.png)
![image](https://user-images.githubusercontent.com/43425012/58103279-1bf94d00-7bb9-11e9-827c-998a79d669fb.png)
![image](https://user-images.githubusercontent.com/43425012/58103313-27e50f00-7bb9-11e9-8ca8-9972c74648f2.png)
![image](https://user-images.githubusercontent.com/43425012/58103343-30d5e080-7bb9-11e9-827b-fb8e5fb82a2d.png)

3 - Calls my Data Layer that is a generic Repository
![image](https://user-images.githubusercontent.com/43425012/58103439-56fb8080-7bb9-11e9-9ccb-a7a260b452ca.png)
![image](https://user-images.githubusercontent.com/43425012/58103452-5f53bb80-7bb9-11e9-878f-2f4dc60b5378.png)
![image](https://user-images.githubusercontent.com/43425012/58103472-6b3f7d80-7bb9-11e9-91dc-a6447bfecfae.png)
![image](https://user-images.githubusercontent.com/43425012/58103501-74c8e580-7bb9-11e9-9af3-6bbb6b6f44d0.png)
![image](https://user-images.githubusercontent.com/43425012/58103513-7beff380-7bb9-11e9-9410-eeec2399d271.png)
![image](https://user-images.githubusercontent.com/43425012/58103528-84e0c500-7bb9-11e9-971c-763e9784fbe9.png)

When I call for the first time to get a Camera, it works fine to get any other camera with different Ids. But when I call to get a Group, it is trying to map to a property that does not existe that is "nu_camera".

The same happens when I call Group and then try to call Camera.

When I call the "GetAllAsync" I have no mapping problems. Each call maps to group or camera entity.

Am I missing something?

**Comment by henkmollema** [comment]
Are the `Group` and `Camera` classes nested classes? E.g. a class in a class?

**Comment by tavaresaraujo** [comment]
Hello @henkmollema.

My classes are not nested.

1 - In my domain layer i have
![image](https://user-images.githubusercontent.com/43425012/58174463-67246600-7c74-11e9-92ac-8ef74064e48d.png)
![image](https://user-images.githubusercontent.com/43425012/58174506-77d4dc00-7c74-11e9-8cda-92123c86d65f.png)
![image](https://user-images.githubusercontent.com/43425012/58174517-7f948080-7c74-11e9-9bb3-b64c665bdd6e.png)

2 - My Application layer is
![image](https://user-images.githubusercontent.com/43425012/58174589-9e931280-7c74-11e9-8d4f-cf939a0573a4.png)
![image](https://user-images.githubusercontent.com/43425012/58174603-a652b700-7c74-11e9-9bd2-b060c3d8b8a9.png)

The wierd thing is that when I use GetAllAsync that uses the same classes it works like well with both Group and Camera classes.

I dont know if it is useful, but here are the methods of my Data Layer of my generic Repository Class:
![image](https://user-images.githubusercontent.com/43425012/58174774-09444e00-7c75-11e9-8dfe-18c7c72463bc.png)

**Comment by henkmollema** [comment]
I'm busy finishing up the 2.0 release of Dommel and after that Dapper.FluentMap 2.0 will follow. These versions might fix these issues, and I'm not planning to release updates or fix issues on the 1.x versions.

I think your best option now is to use [Dommel 2.0](https://www.nuget.org/packages/Dommel/2.0.0-beta4) and use attribute mapping (e.g. `[Column]`) rather than Dapper.FluentMap.Dommel.
