### ISSUE TITLE
Entity ID is an object

### ISSUE THREAD

**Issue by markuznw** [henkmollema/Dommel#136]
Hello and thanks for your work on the library! It has been awesome to use it until now.
I was trying to retrieve the assigned ID from Insert/InsertAsync functions like documented with:

order.Id = await Db.InsertAsync(order);

But the result is an object even if the doc says:
/// <returns>The ID of the inserted entity.</returns>

So I guess a cast to int is missing there ^^
Of course manually casted it to int, but still reporting this little "typo" :)

**Comment by henkmollema** [comment]
The ID of the entity does not necessarily have to be an integer. For example, it can be a GUID generated by the database. It also depends on the size of the number, the database type can map to a `short`, `int` or `long` in C# for example.
