### ISSUE TITLE
Dapper.FluentMap.Dommel error

### ISSUE THREAD

**Issue by marcelogustavoreis** [henkmollema/Dommel#139]
I had this error trying to use the packages from domel v2

the file versions are:
Dapper.FluentMap 2.0.0-beta1
Dapper.FluentMap.Dommel 1.7.0
Dommel 2.0.0-beta5

the error is
Reference to type 'EntityMapBase<,>' claims it is defined in 'Dapper.FluentMap', but it could not be found

what am i doing wrong?

**Comment by henkmollema** [comment]
Those versions aren't compatible. You can't use Dapper.FluentMap with Dommel v2 yet.

**Comment by marcelogustavoreis** [comment]
> Those versions aren't compatible. You can't use Dapper.FluentMap with Dommel v2 yet.

ok. thanks.
