### ISSUE TITLE
SqlExpression expression cannot be null in BETA

### ISSUE THREAD

**Issue by TroySchmidt** [henkmollema/Dommel#155]
In previous versions the expression of SqlExpression could be null and would essentially result in no parameters and an empty whereClause.  This was an easy way to provide a query or select all.  Now it is throwing an error on that not being allowed to be null.  That makes it harder to write logic agnostic data access methods.

**Comment by henkmollema** [comment]
Do you have a code sample on this?

**Comment by henkmollema** [comment]
I'm guessing you mean this method:
```cs
public virtual SqlExpression<TEntity> Where(Expression<Func<TEntity, bool>> expression)
```

Which previously allowed to pass null, e.g. `expr.Where(null)`. I've restored this behavior.
