### ISSUE TITLE
Add deletion by id / ids

### ISSUE THREAD

**Issue by tanguy-carne** [henkmollema/Dommel#170]
Hi ! It's not an issue but it would be nice to have deletion by id and ids
As you do "con.Get\<Product>(1);" you could do "con.Delete\<Product>(1);"

**Comment by henkmollema** [comment]
You can achieve this by doing:
```cs
con.Delete(new Product { Id = 1 });
```

I agree it's a bit hacky. Perhaps adding support for deletion by ID would be nice.

**Comment by lucaxchaves** [comment]
Hi @henkmollema, i would like implement the method below:
```
connection.DeleteMany(Expression<Func<T, bool>> expression)
```
Where the user could delete using lambda expressions, what do you think about it?

**Comment by lucaxchaves** [comment]
Why not use?
```
con.DeleteMultiple<Product>(product => product.Id == 1);
```

**Comment by henkmollema** [comment]
On a second thought I think both options are viable and do not warrant a new method to be added.

**Comment by tanguy-carne** [comment]
True ! :)
And I didn't know DeleteMultiple existed. (Could be nice to have it in a documentation)
Anyway, nice job guys ! For now i'm only using FluentMap, but I keep Dommel in mind.
Have a nice day, and maybe quarantine ;)
