### ISSUE TITLE
SqlServerSqlBuilder problem when using Table with Schema

### ISSUE THREAD

**Issue by codingdna2** [henkmollema/Dommel#189]
When trying to use SqlServerSqlBuilder with a schema name, I get an exception because of the SQL generated (using DataAnnotations or a custom TableNameResolver does the same). 

The generated SQL will be something like:
`select * from [Schema.Table]` 
instead of
`select * from [Schema].[Table]` 

I traced the problem to this piece of code in Resolvers.cs:
```c#
public static string Table(Type type, ISqlBuilder sqlBuilder)
{
    var key = $"{sqlBuilder.GetType()}.{type}";
    if (!TypeTableNameCache.TryGetValue(key, out var name))
    {
        name = sqlBuilder.QuoteIdentifier(DommelMapper.TableNameResolver.ResolveTableName(type));
        TypeTableNameCache.TryAdd(key, name);
    }

    DommelMapper.LogReceived?.Invoke($"Resolved table name '{name}' for '{type}'");
    return name;
}
```

**Solution 1**:
_(Quick and dirty)_. Split the result of ResolveTableName using the "dot" and quote them separately. 
`name = string.Join(".", DommelMapper.TableNameResolver.ResolveTableName(type).Split('.').Select(x => sqlBuilder.QuoteIdentifier(x)));
`

**Solution 2**:
_(Breaking change)_. Include the call to QuoteIdentifier  in the TableNameResolver and not in the Resolvers itself. This would require the ITableNameResolver.ResolveTableName to accept an instance of ISqlBuilder which I've no idea if was ever intended.

**Solution 3**:
_(Breaking change)_. Extend the ITableNameResolver to return separately Schema and Table name and let the Resolvers quote them separately.

I'm running out of imagination so any suggestion is appreciated,
Regards,
Dan

**Comment by henkmollema** [comment]
Interesting, I'll look into it.
