### ISSUE TITLE
Insert doesn't work with properties with `private set`

### ISSUE THREAD

**Issue by matt-lethargic** [henkmollema/Dommel#194]
I've been loving using Dommel for the last week, but now have come across an annoying issue.

My entities all have their properties set to `private set`, I don't want developers to be able to just change properties I want them to call functions on the entity so that any business logic can happen in a DDD manor.

When I try and use `InsertAsync`  Dommel doesn't build any of the fields into the SQL.

Having `private set` properties is a perfectly valid scenario in C#, is there any way that this could be looked at so I don't have to use something like EF Core :-/

**Comment by henkmollema** [comment]
This is fixed with #199.
