### ISSUE TITLE
Same issue as #117

### ISSUE THREAD

**Issue by SH1N081** [henkmollema/Dommel#244]
When working with BaseEntity-classes, Dommel caches the declaring type, so properties will be incorrect for any reflected types.

**Comment by henkmollema** [comment]
Duplicate of #252

**Comment by coding-yak** [comment]
when will this be release to nuget?

**Comment by henkmollema** [comment]
@coding-yak I'll be releasing a new versions this week.

**Comment by coding-yak** [comment]
sweet, thank you! @henkmollema
