### ISSUE TITLE
Resolving properties creating "duplicates"

### ISSUE THREAD

**Issue by SH1N081** [henkmollema/Dommel#245]
When using BaseEntity reflection where the reflected class hides base properties with the "new" keyword, the property resolver will first grab the correct, new properties, but once the array of properties has been created, the base properties have been appended to the array. This will in turn cause an exception when creating (in my case) an insert query, as Dommel now attempts to created parameters for both the reflected properties and the base properties.

**Comment by henkmollema** [comment]
Could you provide a code example of this issue?

**Comment by SH1N081** [comment]
I'll have to get back in my code and see if I can find this again. It may
have been solved by the fix for the issue of reflected classes that you
just merged.

Martin
