### ISSUE TITLE
Multiple Mapping with predicate expression doubt

### ISSUE THREAD

**Issue by korxaq** [henkmollema/Dommel#248]
Hello!

We were trying to do a select using a predicate expression, but the results should have a include with an entity that has a foreign key relation, kinda like:

```cs
var products = con.Select<Product, Category, Product>(p => p.Name.Contains("bike"));
```

so I can have all the products that have bike in the name with the category on each

Is this possible?

Thanks for the amazing component and for the help!

**Comment by henkmollema** [comment]
It's not possible yet. Perhaps automatic multi-mapping can be combined with the `Select` method.

**Comment by henkmollema** [comment]
This has been implemented a while ago.
