### ISSUE TITLE
Nested class and Resolvers.Column

### ISSUE THREAD

**Issue by DanieleSky** [henkmollema/Dommel#252]
Hi, in my project I have this classes (semplified):
```
public class Base {
   public int Id { get; set; }
}

public class Nested1 : Base { }

public class Nested2 : Base { }
```

mapped so:
```
 public class Nested1Map : EntityMap<Nested1>
   {
      public Nested1Map() {
         Map(p => p.Id).ToColumn("id").IsKey();
      }
   }

 public class Nested2Map : EntityMap<Nested2>
   {
      public Nested2Map() {
         Map(p => p.Id).ToColumn("id_2").IsKey();
      }
   }
```

When I use the Method ```Get``` for each nested class, to example:
```
   var value = connection.Get<Nested1>(1);
   var value = connection.Get<Nested2>(1); 
```

I receive the error that in class Nested2 there isn't a valid column name called "Id".

After some research, I think to have found the issue:
in line 144 of [Dommer/Resolvers.cs](https://github.com/henkmollema/Dommel/blob/ccab118182601cb5cb11c1c8c260ecde00e9fef4/src/Dommel/Resolvers.cs#L144) the key of column's cache is built with DeclaringType and not with ReflectedType.
In this case the DeclaringType is always ```Base``` instead of ```Nested1``` or ```Nested2```.

I'm right?
Daniele

**Comment by henkmollema** [comment]
That's correct. `ReflectedType` was not available since .NET Standard 2.0. Since we started using that recently a future version might start using it.
