### ISSUE TITLE
Specify a sequence name

### ISSUE THREAD

**Issue by rafakwolf** [henkmollema/Dommel#26]
Today is not possible to specify a sequence name in a key property.

**Comment by henkmollema** [comment]
What do you mean by 'sequence'. A composite primary key?

**Comment by rafakwolf** [comment]
I'm sorry, ..what i meant was a Microsoft Sql Server sequence.

**Comment by henkmollema** [comment]
How does a key property relate to the underlying type in the database? Could you please elaborate on what you need?

**Comment by rafakwolf** [comment]
a key will automatically incremented if is a identity, or receives value from a sequence. The mapping can be like this:

Map(col => col.Id).IsKeySequence("SEQUENCE_NAME").ToColumn("DB_COL_NAME");

This way i can get value from the sequence into the key column.

**Comment by henkmollema** [comment]
You mean with an `Insert()` query? With the default [`SqlServerQueryBuilder`](https://github.com/henkmollema/Dommel/blob/master/src/Dommel/DommelMapper.cs#L1330) the new id is retrieved with `select scope_identity()`. You could implement your own query builder by using the `ISqlBuilder` interface and register it using:
```csharp
DommelMapper.AddSqlBuilder(typeof(SqlConnection), new SqlServerSequenceSqlBuilder());
```

**Comment by rafakwolf** [comment]
OK, but it does not solve my issue, because each table have a sequence

**Comment by henkmollema** [comment]
Could you show an implementation example.

**Comment by rafakwolf** [comment]
```
        public enum KeyKind
        {
            /// <summary>
            /// Key is a identity
            /// </summary>
            Identity = 1,
            /// <summary>
            /// Key is a sequence by default value 
            /// </summary>
            Sequence = 2,
            /// <summary>
            /// key is a manual
            /// </summary>
            Manual = 3
        }

        /// <summary>
        /// Information of key property
        /// </summary>
        public class InformationKeyProperty
        {
            public PropertyInfo PropertyInfo { get; set; }
            public KeyKind KeyKind { get; set; }
            public string SequenceName { get; set; }
        }



            public string BuildInsert(string tableName, string[] columnNames, string[] paramNames, InformationKeyProperty informationKeyProperty)
            {
                var selectId = String.Empty;

                if (informationKeyProperty.KeyKind == KeyKind.Identity)
                    selectId = "select cast(scope_identity() as decimal)";

                if (informationKeyProperty.KeyKind == KeyKind.Sequence)
                    selectId = string.Format("select cast(current_value as decimal)  from sys.sequences where name = '{0}'", informationKeyProperty.SequenceName);

                return string.Format("set nocount on insert into {0} ({1}) values ({2}) {3}",
                    tableName,
                    string.Join(", ", columnNames),
                    string.Join(", ", paramNames),
                    selectId);
            }

```

**Comment by rafakwolf** [comment]
news about that ?
thanks!

**Comment by rafakwolf** [comment]
@henkmollema any news about sql server sequences ?
thanks!

**Comment by henkmollema** [comment]
This feature seems like niche and SQL Server specific feature which is out of scope for this library. I still think you could implement this in your own `ISqlBuilder` implementation.
