### ISSUE TITLE
modulo in predicate is not working with sqlite connection

### ISSUE THREAD

**Issue by ahmedsafan86** [henkmollema/Dommel#261]
.net core 5.0
Dommel, Version=2.3.0.0
the following line fail
` _dbConnection.SelectAsync(user => user.Id%2 == 0 )`

With error 
` Message: 
    System.Data.SQLite.SQLiteException : SQL logic error
    near "MOD": syntax error
  Stack Trace: 
    SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
    SQLiteCommand.BuildNextCommand()
    SQLiteCommand.GetStatement(Int32 index)
    SQLiteDataReader.NextResult()
    SQLiteDataReader.ctor(SQLiteCommand cmd, CommandBehavior behave)
    SQLiteCommand.ExecuteReader(CommandBehavior behavior)
    SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
    DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)`

output sql is
`select * from Users where (Id MOD @p1 = @p2)`

**Comment by henkmollema** [comment]
Can you try this again with version 2.3.2?
