### ISSUE TITLE
DatabaseGeneratedOption.None not working

### ISSUE THREAD

**Issue by VillaltaJose** [henkmollema/Dommel#269]
When using a custom primary key (in most cases varchar keys), dommel tries to put an auto increment key ignoring the SetGeneratedOption(DatabaseGeneratedOption.None) property.

**Comment by henkmollema** [comment]
What do you mean with `SetGeneratedOption(DatabaseGeneratedOption.None)`? Can you share an example of your model configuration?

**Comment by henkmollema** [comment]
There is a [test case](https://github.com/henkmollema/Dommel/blob/master/test/Dommel.IntegrationTests/InsertNonGeneratedColumnTests.cs) which verifies this behavior. Please let me know if it's still not working for you.

**Comment by denovellis** [comment]
I'm having the same issue.  Here is a code sample : 

` public class TestMap : DommelEntityMap<Test>
 {
     public TestMap()
     {
         ToTable("Business");

         Map(p => p.test_id).ToColumn("Id", caseSensitive: true).IsKey()
             .SetGeneratedOption(DatabaseGeneratedOption.None);

         Map(p => p.test_name).ToColumn("Name", caseSensitive: true);
         Map(p => p.test_count).ToColumn("Count", caseSensitive: true);
     }
 }`
