### ISSUE TITLE
MultiMap and Inner Joins

### ISSUE THREAD

**Issue by rafakwolf** [henkmollema/Dommel#27]
The multimap feature writes always "inner joins", but sometimes you will need a "left join".
Perhaps verify if the reference property is a nullable, and in this case uses a left join.

**Comment by henkmollema** [comment]
I'd like this suggestion, I'll look into it!

**Comment by henkmollema** [comment]
Fixed this in fdb991d86d9119b56919b834ae8ce8c971836145, will be deployed with the next release.
