### ISSUE TITLE
SQLExpression does not use column mapping

### ISSUE THREAD

**Issue by fernandocristan** [henkmollema/Dommel#271]
Hello, I have the following mapping

`ToTable("pro_categoria");`
`Map(x => x.Cod).IsKey().IsIdentity().ToColumn("cod", false);`
`Map(x => x.Descricao).ToColumn("descricao", false);`
`Map(x => x.Ativo).ToColumn("ativo", false);`

When performing a search using sqlExpression, columns are not mapped

`_conn.From<Categoria>(x => `
`                               x.Select(x => new { x.Cod, x.Descricao })`
`                               .Where(y => y.Cod == 1))`

Generated sql = `select "Cod", "Descricao" from "pro_categoria" where ("cod" = @p1)`

**Comment by picchi-lucas** [comment]
As a workaraund you can create a Dto to select only the columns you need, and use this like this (preventing overselection):

- Declare DTO

```csharp
public record CategoriaDto()
{
    public string Cod{ get; init; } = default!;
    public string Descricao { get; init; } = default!;
}
```
- Decalre Map for DTO

```csharp
    public class CategoriaDtoMap : DommelEntityMap<CategoriaDto>
    {
        public CategoriaDtoMap ()
        {
            ToTable("pro_categoria");
            Map(x => x.Cod).IsKey().IsIdentity().ToColumn("cod", false);
            Map(x => x.Descricao).ToColumn("descricao", false);
        }
    }
```

- Use DTO in query to only select the columns you need with the correct name mapping

```csharp
  _conn.From<CategoriaDto>(x =>
  x.Select(x => new CategoriaDto())
  .Where(y => y.Cod == 1))
```

This will generate your SQL without overselecting and with correct mapping

**Comment by fernandocristan** [comment]
Thanks!
