### ISSUE TITLE
missing selectAsync with joins

### ISSUE THREAD

**Issue by nerolauda** [henkmollema/Dommel#277]
In the readme there is written:
"var products = await connection.SelectAsync<Product, Category, Product>(x => x.Name.StartsWith("bike"));"
But in nuget package 2.0.0. there is not such a method with 3 generics.
Can you release such a method or remove it from documentation?
Moreover: it could be very useful to have also  a FromAsync <T1,T2,T3>...

**Comment by henkmollema** [comment]
These methods are available starting from v3.0.0: https://www.nuget.org/packages/Dommel/3.0.0.

I'm working on a prototype of `FromAsync` with joins, but it turns out to be pretty complicated 😄.
