### ISSUE TITLE
Resolving foreign key properties

### ISSUE THREAD

**Issue by tborgesa** [henkmollema/Dommel#28]
Hi,

In your implementation default of interface `IForeignKeyPropertyResolver` you only get the name of type + `Id`, but there is any property in the database that not follow this rule.

Maybe you can create a method in  `DommelEntityMa`p that set a name of FK Property and in the method `ResolveForeignKeyProperty` get this name or return this role above.

Thanks.

**Comment by henkmollema** [comment]
Hi,

Nice idea, I was planning to add something like this. Note that version 1.4 is still in beta. Please keep any suggestions coming :smile: 

Regards

**Comment by henkmollema** [comment]
This should be fixed by Dapper.FluentMap.Dommel. Closing this issue here.
https://github.com/henkmollema/Dapper-FluentMap/issues/30
