### ISSUE TITLE
Automatic multi mapping N-hierarchy

### ISSUE THREAD

**Issue by rafaelsakai** [henkmollema/Dommel#289]
Hi! How can I create a automatic multi mapping with this hierarchy:

Class -> SubClass -> SubClassOfSubClass

With one level of hierarchy works well:

`var class  = product.Get<Class, SubClass, Class>(1);`

But with one more level of hierarchy doesn't work, the SubClassOfSubClass cames null:

`var class = product.Get<Class, SubClass, SubClassOfSubClass, Class>(1);`

Tks

**Comment by henkmollema** [comment]
This is not supported in Dommel and probably will never be.
