### ISSUE TITLE
Conflict in select with inner join

### ISSUE THREAD

**Issue by tborgesa** [henkmollema/Dommel#29]
Hi,

In my database there is many table that have columns with same name. When you use `select * from` the database return an exception.
Perhaps, you use the mapping for especification the name of column in the select clause.

Thank you for all.

**Comment by henkmollema** [comment]
@tborgesa do you have a repro for this? I can't quite follow what you mean.

**Comment by rafakwolf** [comment]
´´´sql
select * from Paroquias p
join Dioceses d on (d.ID = p.IDDIOCESE)
where ID = 2
´´´
In this case Paroquias and Dioceses has a ID field.

Then occurs the exception ( "Ambiguous column name 'ID'."  )

**Comment by henkmollema** [comment]
Dommel will include the table name for the `WHERE`-clause. E.g.:
```sql
select * from Foo f
inner join Bar b on f.Id = b.FooId
where f.Id = @Id
```
