### ISSUE TITLE
Multi-level foreign key relationships

### ISSUE THREAD

**Issue by igordamasceno96** [henkmollema/Dommel#301]
**Guys, how could I implement such a scenario using dommel?**

```
public class Category
{
public int CategoryId { get; set; }
public string Description { get; set; }
publict list<CategoryRule> rules { get; set; }
}

public class CategoryRule
{
public int CategoryRuleId { get; set; }
public string Description { get; set; }
publict int UserId { get; set; }
public User UserRule{get;set;}
}

public class User
{
publict int UserId { get; set; }
public string Name { get; set; }
}

```

**I tried to use it, but it didn't work properly.**
`
Connection.GetAsync<ClientCategory, ClientCategoryRule, User, ClientCategory>(id); `

Could someone help me?

@henkmollema @linjiacheng @samuelpampolini @renefc3 @lucaxchaves

**Comment by henkmollema** [comment]
This is not possible with Dommel unfortunately. You should create two separate queries, or a raw SQL query using Dapper.

**Comment by igordamasceno96** [comment]
Understood. Thank you for your attention
