### ISSUE TITLE
IDbTransaction into Select method

### ISSUE THREAD

**Issue by rafakwolf** [henkmollema/Dommel#31]
Method Select for predicate filters needs a transaction param.

**Comment by TroySchmidt** [comment]
Has this been abandoned then?  Or should I make a pull request and attempt to fix this?

**Comment by 303248153** [comment]
I need this too because I get this error when I use GetAll<T> after BeginTransaction:

``` text
ExecuteNonQuery requires the command to have a transaction when the connection assigned to the command is in a pending local transaction. The Transaction property of the command has not been initialized. 
```

**Comment by henkmollema** [comment]
This is fixed in v2.
