### ISSUE TITLE
No is possible install the package on ".Net Framework=4.5"

### ISSUE THREAD

**Issue by andresantos78** [henkmollema/Dommel#45]
Hi Henk Mollema.

I'm trymng install the package into class library project that use ".Net Framework 4.5".

I'm using your project as an alternative to EntityTypeConfiguration for Dapper and would like to be able to map the name of my tables.

This can be considered as a feature or am using the wrong package?

Thank you for your initiative.
Great Job!

**Comment by henkmollema** [comment]
Hi @andresantos78, which version do you use? Dommel does target .NET 4.5: https://www.nuget.org/packages/Dommel.

**Comment by andresantos78** [comment]
Hi Henk Mollema.

I'm attaching one print for explain the error to install the package.
See also the image.  
![erro-install-dapper-fluentmap-dommel](https://cloud.githubusercontent.com/assets/7697497/17697766/18666d7c-638d-11e6-8dd3-f19046172fcf.png)

Thank you for your attention

**Comment by henkmollema** [comment]
Ah I see. You are trying to download [Dapper.FluentMap.Dommel](https://www.nuget.org/packages/Dapper.FluentMap.Dommel/1.4.1), which is a [Dapper.FluentMap](https://github.com/henkmollema/Dapper-FluentMap) extension for Dommel. Apparently it did not target .NET 4.5, I'm not sure why. I've just uploaded [v1.4.2](https://www.nuget.org/packages/Dapper.FluentMap.Dommel/1.4.2) which targets .NET 4.5 as well.

If you just need Dommel, install the other package in your image: just 'Dommel'.

If
