### ISSUE TITLE
Invalid Column Map 

### ISSUE THREAD

**Issue by IvAlex1986** [henkmollema/Dommel#48]
Hello,
We have the trouble with Dommel.

We use: MySQL 5.6.15 + Dapper 1.50.2 + Dommel 1.6.0 + Dapper.FluentMap.Dommel 1.4.0

Our Model:

``` C#
public class AppCityList
{
    public int Id { get; set; }
    public string CityName { get; set; }
    public int StateId { get; set; }
    public int CountryId { get; set; }
}
```

Our Mapping class:

``` C#
public class AppCityListMap : DommelEntityMap<AppCityList>
{
    public AppCityListMap()
    {
        ToTable("app_city_list");
        Map(p => p.Id).IsKey();
        Map(p => p.CityName).ToColumn("City_Name");
        Map(p => p.StateId).ToColumn("State_Id");
        Map(p => p.CountryId).ToColumn("Country_Id");
    }
}
```

We have added mapper using next command:

``` C#
FluentMapper.Initialize(config => { config.AddMap(new AppCityListMap()); });
```

We try to run query using next command:

``` C#
private TU GetSingle<TU>(Expression<Func<TU, bool>> predicate)
{
    using (var con = ConnectionFactory.GetReadOnlyConnection())
    {
        var connection = con;
        return Action(con, () =>
        {
            var entities = connection.Select(predicate);
            return entities.FirstOrDefault();
        });
    }
}

public AppCityList GetCityByNameAndStateIdAndCountryId(String cityName, Int32 stateId, Int32 countryId)
{
    return GetSingle<AppCityList>(a => a.CityName == cityName && a.CountryId == countryId && a.StateId == stateId);
}
```

But our SQL looks like this:
select \* from app_city_list where CityName = @p0 and CountryId = @p1 and StateId = @p2

And we have an error:
Unknown column 'CityName' in 'where clause'

This error occurs because only City_Name column exists in our table app_city_list.
Could you help with the problem of improper mapping work?

**Comment by henkmollema** [comment]
You're probably missing the Dommel integration in your Dapper.FluentMap configuration. You have to call `ForDommel()` on the configuration instance like this:

```csharp
FluentMapper.Initialize(config => { config.AddMap(new AppCityListMap()).ForDommel(); });
```

**Comment by huhubun** [comment]
Hi Henk,
I have this problem too, and I'm very sure I called `config.ForDommel()`
```CSharp
    FluentMapper.Initialize(config =>
    {
        config.AddMap(new HotelMap());
        config.ForDommel();
    });
```

But there are a little different in entity class, it derived from a base class
```CSharp
    public class Hotel : BaseEntity
    {
        public string Description { get; set; }
    }

    public class BaseEntity
    {
        public string Code { get; set; }
    }
```

mapping class is
```CSharp
    public class HotelMap : DommelEntityMap<Hotel>
    {
        public HotelMap()
        {
            ToTable("hotels");

            Map(t => t.Description).ToColumn("des");
            Map(t => t.Code).ToColumn("hotel_code");
        }
    }
```

If the `Code` property defined in the `Hotel` class, and everything is OK.
I use Dapper 1.50.2 + Dommel 1.6.1 + Dapper.FluentMap.Dommel 1.4.2, and also tried Dommel 1.7.1

Could you make it work with base class? 
Thanks.

**Comment by jmreynolds** [comment]
@huhubun - your problem is fixed in [Dapper.FluentMap 1.5.1](https://github.com/henkmollema/Dapper-FluentMap/commit/86fb02afe6210fc30953bca738c6d6ac7fb7c596) - see [The corresponding Pull Request](https://github.com/henkmollema/Dapper-FluentMap/pull/24)

**Comment by huhubun** [comment]
@jmreynolds - I tried the version you mentioned, but it seems the issue hasn't been fixed, thanks anyway.

**Comment by henkmollema** [comment]
@huhubun there is a indeed an issue with derived entities. I still have to look into that...

**Comment by henkmollema** [comment]
@IvAlex1986 is your issue resolved? Please re-open if it's not.
