### ISSUE TITLE
Insert error - Cannot insert explicit value for identity column in table 'YouTableName' when IDENTITY_INSERT is set to OFF.

### ISSUE THREAD

**Issue by LiveLikeLastDay** [henkmollema/Dommel#49]
Cannot insert explicit value for identity column in table 'category' when IDENTITY_INSERT is set to OFF.

```
 private static string BuildInsertQuery(IDbConnection connection, Type type)
        {
            string sql;
            if (!_insertQueryCache.TryGetValue(type, out sql))
            {
                var tableName = Resolvers.Table(type);
                var keyProperty = Resolvers.KeyProperty(type);
                var typeProperties = Resolvers.Properties(type)
                                              .Where(p => p != keyProperty || keyProperty.GetSetMethod() != null)
                                              .Where(p => p.GetSetMethod() != null)
                                              .ToArray();

                var columnNames = typeProperties.Select(Resolvers.Column).ToArray();
                var paramNames = typeProperties.Select(p => "@" + p.Name).ToArray();

                var builder = GetBuilder(connection);

                sql = builder.BuildInsert(tableName, columnNames, paramNames, keyProperty);

                _insertQueryCache[type] = sql;
            }

            return sql;
        }
```

I think this line of code is a bug:
```
 .Where(p => p != keyProperty || keyProperty.GetSetMethod() != null)
```

The old version works fine;

```
Resolvers.Properties(type).Where(p => p != keyProperty).ToList();  
```

**Comment by henkmollema** [comment]
It should work if you remove the setter (e.g. `set;`) in your POCO.

**Comment by enterpub** [comment]
Hello, I'm experiencing same issue. I have a table with Id column, which is primary key and identity,
`Id bigint IDENTITY(1, 1) NOT NULL`

 I have a class Token, works with table Token
```
public sealed class Token
    {
        public long Id { get; set; }
        public string Token { get; set; }
    }
```

when I trying to insert new record with method:
```
public void CreateToken(Token token)
        {
            using (var connection = CreateConnection())
            {
                connection.Insert(token);
            }
        }
```
I get an the above exception. The query, generated, by Dommel looks like this:
```
exec sp_executesql N'set nocount on insert into Token (Id, Token) values (@Id, @Token) select cast(scope_identity() as int)',
N'@Id bigint,@Token nvarchar(4000)',
@Id=0,@Token=N'8d539f27-71fd-49b2-897d-0837d85580bbd882a1e3-90f3-46bf-8005-a51e9af65b8f'
```

The problem is: generated query must not contain Id column and @Id parameter. It should look like this:
```
exec sp_executesql N'set nocount on insert into Token (Token) values (@Token) select cast(scope_identity() as int)',
N'@Token nvarchar(4000)',
@Token=N'8d539f27-71fd-49b2-897d-0837d85580bbd882a1e3-90f3-46bf-8005-a51e9af65b8f'
```
How to achieve such behaviour? Is there a way to say Dommel that a column is and identity column?

**Comment by henkmollema** [comment]
@LiveLikeLastDay @enterpub this should be fixed in v1.7.3: https://www.nuget.org/packages/Dommel/1.7.3

FYI: you can use the `[Key]` attribute to explicitly specify the key property for a type so it will be ignored when building queries.

**Comment by ahoka** [comment]
Hi,

This change breaks the case when the Id actually comes from the application. This is breaking existing applications using Dommel.

**Comment by henkmollema** [comment]
I understand @ahoka. Although it was never the intention to set the primary key from the application side. However, I do think it might be a nice feature. I'm not sure yet how to implement both cases correctly without too much need for configuration. If someone of you have any suggestions, please share them.

**Comment by henkmollema** [comment]
@LiveLikeLastDay @enterpub @ahoka 
I've update the `IKeyPropertyResolver` interface so that it indicates whether a property is a an identity. This behavior can be configured. Dapper.FluentMap.Dommel will provide support for this soon.

See a7653b0cc6423abc9cce2c0a880ec1f8f3d9422f.

**Comment by henkmollema** [comment]
[Dapper.FluentMap.Dommel](https://www.nuget.org/packages/Dapper.FluentMap.Dommel) now supports configuring the identity of a property.
