### ISSUE TITLE
Lock dictionary caches to prevent duplicate key insert

### ISSUE THREAD

**Issue by UmairB** [henkmollema/Dommel#52]
Currently all the query cache's are stored in dictionaries with 

`if (!dictionary.hasKey(type)) { //build sql based off of type and store in dictionary }`

logic. Problems occur when more than on thread/request hit the same bit of code at the same time. Causes exceptions to occur (typical dictionary key + multi-threading issues).

**Comment by henkmollema** [comment]
@UmairB yes, this needs refactoring to a `ConcurrentDictionary` and correct accessing the data. You can send a PR if you'd like.

**Comment by henkmollema** [comment]
@UmairB fixed in v1.7.3: https://www.nuget.org/packages/Dommel/1.7.3
