### ISSUE TITLE
Dommel ignores DateTimeOffset properties

### ISSUE THREAD

**Issue by enterpub** [henkmollema/Dommel#53]
My table contains `datetimeoffset(0)` column and respected class has `DateTimeOffset` property. Current implementation ignores such properties. That is because `PropertyResolverBase.PrimitiveTypes` property does not contain `DateTimeOffset` type in its HashSet.
There is a way to resolve this issue by inheriting from `DefaultPropertyResolver` and override 'PrimitiveTypes' property.

```
public sealed class CustomPropertyResolver : DommelMapper.DefaultPropertyResolver
        {
            protected override HashSet<Type> PrimitiveTypes => new HashSet<Type>(new[]
                                                                                     {
                                                                                        typeof(object),
                                                                                        typeof(string),
                                                                                        typeof(Guid),
                                                                                        typeof(decimal),
                                                                                        typeof(double),
                                                                                        typeof(float),
                                                                                        typeof(DateTime),
                                                                                        typeof(DateTimeOffset),
                                                                                        typeof(TimeSpan)
                                                                                     });
        }
```
Then register `CustomPropertyResolver` somewhere in startup like 'DommelMapper.SetPropertyResolver(new CustomPropertyResolver());'

Would be great if @henkmollema fix it.
BTW, I'm using .NET Core 1.0.1 if it matters

**Comment by henkmollema** [comment]
@enterpub would you like to send a PR that includes `DateTimeOffset` in the default implementation?

**Comment by enterpub** [comment]
@henkmollema I'll try, have not done this before. But I'm available to do this on weekends

**Comment by henkmollema** [comment]
@enterpub fixed in fixed in v1.7.3: https://www.nuget.org/packages/Dommel/1.7.3

**Comment by henkmollema** [comment]
Oops, haha. I'm sorry if I went ahead of you.

**Comment by enterpub** [comment]
@henkmollema thank you for nuget package so fast
