### ISSUE TITLE
Oracle support

### ISSUE THREAD

**Issue by Wintermute79** [henkmollema/Dommel#55]
Do you intend to support Oracle?
I am currently using FluentMap and would like to add Dommel for CRUD. But at the moment only Dapper-Extensions seems to have Oracle support.
See https://github.com/tmsmith/Dapper-Extensions/blob/master/DapperExtensions/Sql/OracleDialect.cs

**Comment by henkmollema** [comment]
I've no intention of adding Oracle support myself. However you're free to send a PR.
