### ISSUE TITLE
PropertyResolverBase.FilterComplexTypes removes byte[]

### ISSUE THREAD

**Issue by ryudice** [henkmollema/Dommel#67]
PropertyResolverBase.FilterComplexTypes removes byte[] which is a valid SQL server type.

**Comment by henkmollema** [comment]
That's an error indeed. Would you like to send a PR?

**Comment by ryudice** [comment]
Working on it

**Comment by ryudice** [comment]
https://github.com/henkmollema/Dommel/pull/68

**Comment by henkmollema** [comment]
Closed with #68.
