### ISSUE TITLE
Foreign Key Problems

### ISSUE THREAD

**Issue by michaelvilarino** [henkmollema/Dommel#72]
I'm having trouble working with a foreign key.

inside a class, I need to put the name of a property + "Id" so that it is recognized as foreign key.

This is not legal ..

Would not it be better to specify a foreign key at the time of mapping?

For example:

ToTable ("Component");
Map (m => m.Id) .Iskey ();
Map (m => Description);
Map (m => m.Product) .IsForeignKey (); // Suggestion

**Comment by henkmollema** [comment]
Dommel v2 will support the `[ForeignKey]` attribute which allows you to specify the property name of the foreign key.

**Comment by MichaelRodrigueess0s1** [comment]
how i'm use the ForeignKey attribute?
