### ISSUE TITLE
Like

### ISSUE THREAD

**Issue by ronneylira** [henkmollema/Dommel#78]
Hi,

is there a way to perform a like operation, such as contains?

the query i'm trying to achieve is this: 
`var result = _repository.GetList(r=> r.ImageName.Contains("yellow");`

**Comment by henkmollema** [comment]
Today the `Contains` method is not supported, Dommel does not have a fully-featured LINQ provider like Entity Framework does. However, I think that the `Contains` operator might be a useful feature. I'll add it to the backlog.

**Comment by henkmollema** [comment]
This will be added by #83.
