### ISSUE TITLE
Insert does not work for dommel in postgres with table name - TableName

### ISSUE THREAD

**Issue by himaanshugoyal** [henkmollema/Dommel#88]
"42P01: relation \\\"specialistportfolios\\\" does not exist"

My Table name is SpecialistPortfolios and dommel is not able to map automatically in insert postgres

**Comment by henkmollema** [comment]
What does that error mean? Does the relation exists?

**Comment by henkmollema** [comment]
@himaanshugoyal  I hope my suggestions works out for you. If not, please reopen this issue.
